esphome:
  name: igrill

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://bendikwa/esphome-igrill@v1.2

esp32_ble_tracker:

ble_client:
  - mac_address: 70:91:8F:XX:XX:XX
    id: igrill_v3
    on_connect:
      then:
        - binary_sensor.template.publish:
            id: v3_connection_bin
            state: ON
    on_disconnect:
      then:
        - binary_sensor.template.publish:
            id: v3_connection_bin
            state: OFF

sensor:
  - platform: igrill
    ble_client_id: igrill_v3
    update_interval: 30s # default
    send_value_when_unplugged: true # default
    unplugged_probe_value: 0 # default
    battery_level:
      name: "IGrill v3 battery"
    temperature_probe1:
      name: "IGrill v3 temp probe 1"
    temperature_probe2:
      name: "IGrill v3 temp probe 2"
    temperature_probe3:
      name: "IGrill v3 temp probe 3"
    temperature_probe4:
      name: "IGrill v3 temp probe 4"
    propane_level:
      name: "IGrill v3 Propane level"
 
binary_sensor:
  - platform: template
    name: "iGrill v3 connection status"
    id: v3_connection_bin
    device_class: connectivity
    entity_category: diagnostic
  - platform: igrill
    ble_client_id: igrill_v3
    update_interval: 30s # default
    temperature_probe1_plugged:
      name: "IGrill v3 temp probe 1 Plugged"
    temperature_probe2_plugged:
      name: "IGrill v3 temp probe 2 Plugged"
    temperature_probe3_plugged:
      name: "IGrill v3 temp probe 3 Plugged"
    temperature_probe4_plugged:
      name: "IGrill v3 temp probe 4 Plugged"
